CREATE TABLE ESTIMATED_PRICE_GROUP
(
	OBJECTID INT NOT NULL UNIQUE,
	ESTIMATED_PRICE_GROUP INT
)
GO

BULK INSERT ESTIMATED_PRICE_GROUP
    FROM '[path]' -- here change path
    WITH
    (
    FIRSTROW = 1,
    FIELDTERMINATOR = ',',  -- CSV field delimiter
    ROWTERMINATOR = '\n',
    ERRORFILE = '[path]', -- here change path
    TABLOCK
    )

CREATE CLUSTERED INDEX ObjectIDIndex ON dbo.ESTIMATED_PRICE_GROUP(OBJECTID)

UPDATE PARCEL_VECTORS SET PARCEL_VECTORS.Price_Group_int = E.ESTIMATED_PRICE_GROUP
	FROM PARCEL_VECTORS P
	INNER JOIN ESTIMATED_PRICE_GROUP E
	ON P.OBJECTID = E.OBJECTID;
	GO